# Netlify configuration
[build]
  command = "npm run build"
  publish = "dist/hair-salon-app/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

